### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@edx/platform-team: I marked this as yours, but I'm not sure that's the best ownership assignment or not... It looks a bit abandoned.

**Comment by doctoryes** [comment]
Where should tools like the ones in this repo be placed today? Who owns *that* repo?

**Comment by cpennington** [comment]
Good question. Several teams have their own repos (edx/testeng-ci and edx/repo-tools for @edx/testeng and @edx/openedx-tooling, in particular).

**Comment by cpennington** [comment]
There might be a better pattern, though, so that there isn't as much siloing of teams.

**Comment by doctoryes** [comment]
OK - we'll take this one. 👍 

I've listed the tools locations in the nascent Developer Hub:
https://openedx.atlassian.net/wiki/display/ENG/OpenEdx+Developer+Resource+Hub#OpenEdxDeveloperResourceHub-ToolsRepositories

**Pull request merged**
